package com.ssafy.leaper.global.error;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

  /* 1. COMMON – 공통 */
  COMMON_INVALID_FORMAT(HttpStatus.BAD_REQUEST, "COMMON-001"),
  COMMON_INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "COMMON-002"),
  COMMON_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "COMMON-003"),
  COMMON_ENTITY_NOT_FOUND(HttpStatus.NOT_FOUND, "COMMON-004"),
  COMMON_BAD_REQUEST(HttpStatus.BAD_REQUEST, "COMMON-005"),

  /* 2. AUTH – 인증/인가 */
  AUTH_INVALID_TOKEN(HttpStatus.UNAUTHORIZED, "AUTH-001"),
  AUTH_ACCESS_DENIED(HttpStatus.FORBIDDEN, "AUTH-002"),
  AUTH_DUPLICATE_ACCOUNT(HttpStatus.CONFLICT, "AUTH-003"),

  /* 2-1. JWT – JWT 토큰 */
  JWT_INVALID_HEADER(HttpStatus.UNAUTHORIZED, "JWT-001"),
  JWT_INVALID_TOKEN(HttpStatus.UNAUTHORIZED, "JWT-002"),
  JWT_EXPIRED_TOKEN(HttpStatus.UNAUTHORIZED, "JWT-003"),
  JWT_INVALID_REGISTRATION_TOKEN(HttpStatus.UNAUTHORIZED, "JWT-004"),

  /* 3. USER – 사용자 */
  USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER-001"),
  USER_DUPLICATE_NICKNAME(HttpStatus.CONFLICT, "USER-002"),
  USER_NICKNAME_CHANGE_LIMITED(HttpStatus.FORBIDDEN, "USER-003"),
  USER_RE_REGISTRATION_FORBIDDEN(HttpStatus.FORBIDDEN, "USER-004"),
  USER_LOGIN_FAIL(HttpStatus.UNAUTHORIZED, "USER-005"),
  USER_SIGN_UP_FAIL(HttpStatus.UNAUTHORIZED, "USER-006"),

  /* PLATFORM_ACCOUNT – 계정 */
  PLATFORM_ACCOUNT_NOT_FOUND(HttpStatus.NOT_FOUND, "PLATFORM-001"),

  /* CONTENT - 컨텐츠 */
  CONTENT_NOT_FOUND(HttpStatus.NOT_FOUND, "CONTENT-001"),

  /* CHAT – 채팅 */
  CHAT_ROOM_NOT_FOUND(HttpStatus.NOT_FOUND, "CHAT-001"),
  CHAT_ROOM_ACCESS_DENIED(HttpStatus.FORBIDDEN, "CHAT-002"),
  CHAT_MESSAGE_NOT_FOUND(HttpStatus.NOT_FOUND, "CHAT-003"),
  CHAT_FILE_UPLOAD_FAILED(HttpStatus.BAD_REQUEST, "CHAT-004"),
  CHAT_INVALID_MESSAGE_TYPE(HttpStatus.BAD_REQUEST, "CHAT-005"),
  CHAT_INVALID_USER_TYPE(HttpStatus.BAD_REQUEST, "CHAT-006"),

  /* INFLUENCER – 인플루언서 */
  INFLUENCER_NOT_FOUND(HttpStatus.NOT_FOUND, "INFLUENCER-001"),
  INFLUENCER_DUPLICATE_NICKNAME(HttpStatus.CONFLICT, "INFLUENCER-002"),
    DUPLICATE_NICKNAME(HttpStatus.CONFLICT, "INFLUENCER-003"),
    DUPLICATE_SOCIAL_ACCOUNT(HttpStatus.CONFLICT, "INFLUENCER-004"),

  /* ADVERTISER – 광고주 */
  ADVERTISER_NOT_FOUND(HttpStatus.NOT_FOUND, "ADVERTISER-001"),
  ADVERTISER_DUPLICATE_EMAIL(HttpStatus.CONFLICT, "ADVERTISER-002"),
  DUPLICATE_LOGIN_ID(HttpStatus.CONFLICT, "ADVERTISER-003"),
  DUPLICATE_BUSINESS_REG_NO(HttpStatus.CONFLICT, "ADVERTISER-004"),
  INVALID_BUSINESS_REG_NO(HttpStatus.BAD_REQUEST, "ADVERTISER-005"),

  /* FILE – 파일 */
  FILE_NOT_FOUND(HttpStatus.NOT_FOUND, "FILE-001"),
  FILE_UPLOAD_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "FILE-002");

  private final HttpStatus httpStatus;
  private final String code;
}
